#!/usr/bin/python3

import cgitb
cgitb.enable()

print("Content-type:text/html")
print()

import sqlite3
from helper import create_json, get_input

connection = sqlite3.connect('database/memes.db')
sql = connection.cursor()

